definitions:
  models.BulkCreateDriverLocationRequest:
    properties:
      locations:
        items:
          $ref: '#/definitions/models.CreateDriverLocationRequest'
        type: array
    required:
    - locations
    type: object
  models.CreateDriverLocationRequest:
    properties:
      latitude:
        maximum: 90
        minimum: -90
        type: number
      longitude:
        maximum: 180
        minimum: -180
        type: number
    required:
    - latitude
    - longitude
    type: object
  models.DriverLocation:
    properties:
      id: {}
      location:
        $ref: '#/definitions/models.Location'
    type: object
  models.Location:
    properties:
      coordinates:
        items:
          type: number
        type: array
      type:
        type: string
    type: object
  models.SearchDriverLocationRequest:
    properties:
      latitude:
        maximum: 90
        minimum: -90
        type: number
      longitude:
        maximum: 180
        minimum: -180
        type: number
      radius:
        minimum: 0
        type: number
    required:
    - latitude
    - longitude
    - radius
    type: object
info:
  contact: {}
  description: This is a sample API.
  title: Driver Location API
  version: "1.0"
paths:
  /drivers:
    post:
      consumes:
      - application/json
      description: Create a driver location
      parameters:
      - description: Location
        in: body
        name: location
        required: true
        schema:
          $ref: '#/definitions/models.CreateDriverLocationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Driver location created
          schema:
            type: string
        "400":
          description: Invalid JSON
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Create a driver location
      tags:
      - drivers
  /drivers/bulk:
    post:
      consumes:
      - application/json
      description: Bulk create driver locations
      parameters:
      - description: Locations
        in: body
        name: locations
        required: true
        schema:
          $ref: '#/definitions/models.BulkCreateDriverLocationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Driver locations created
          schema:
            type: string
        "400":
          description: Invalid JSON
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Bulk create driver locations
      tags:
      - drivers
  /drivers/search:
    post:
      consumes:
      - application/json
      description: Search driver locations
      parameters:
      - description: Search request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SearchDriverLocationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Driver locations
          schema:
            items:
              $ref: '#/definitions/models.DriverLocation'
            type: array
        "400":
          description: Invalid JSON
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Search driver locations
      tags:
      - drivers
  /drivers/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a CSV file to bulk create driver locations
      produces:
      - application/json
      responses:
        "201":
          description: Driver locations created
          schema:
            type: string
        "400":
          description: Invalid file
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Upload a CSV file to bulk create driver locations
      tags:
      - drivers
  /healthz:
    get:
      description: Health check
      responses:
        "200":
          description: OK
          schema:
            type: string
        "503":
          description: Service unavailable
          schema:
            type: string
      summary: Health check
      tags:
      - health
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
